version: '3.3'
services:
 web:
  image: nginx
  container_name: webserver
  ports:
   - 80:80
   - 443:443
 databases:
   image: mysql
   ports:
    - "3306:3306"
   environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=demodb

